In [1]:
import pandas as pd
import numpy as np

In [2]:
data = [12, 'desktop', 1, 2, 'credit card', 'male', 2, 3, 'fashion', 2, 'single', 3, 0, 13.0, 10, 20, 160.0]

In [3]:
columns = ['Tenure', 'PreferredLoginDevice', 'CityTier', 'WarehouseToHome', 'PreferredPaymentMode', 'Gender',
               'HourSpendOnApp', 'NumberOfDeviceRegistered', 'PreferredOrderCat', 'SatisfactionScore',
               'MaritalStatus', 'NumberOfAddress', 'Complain', 'OrderAmountHikeFromLastYear', 'OrderCount',
               'DaySinceLastOrder', 'CashbackAmount']

input_df = pd.DataFrame([data], columns=columns)

In [4]:
input_df

Tenure PreferredLoginDevice  CityTier  WarehouseToHome  \
0      12              desktop         1                2   

  PreferredPaymentMode Gender  HourSpendOnApp  NumberOfDeviceRegistered  \
0          credit card   male               2                         3   

  PreferredOrderCat  SatisfactionScore MaritalStatus  NumberOfAddress  \
0           fashion                  2        single                3   

   Complain  OrderAmountHikeFromLastYear  OrderCount  DaySinceLastOrder  \
0         0                         13.0          10                 20   

   CashbackAmount  
0           160.0

In [5]:
input_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Tenure                       1 non-null      int64  
 1   PreferredLoginDevice         1 non-null      object 
 2   CityTier                     1 non-null      int64  
 3   WarehouseToHome              1 non-null      int64  
 4   PreferredPaymentMode         1 non-null      object 
 5   Gender                       1 non-null      object 
 6   HourSpendOnApp               1 non-null      int64  
 7   NumberOfDeviceRegistered     1 non-null      int64  
 8   PreferredOrderCat            1 non-null      object 
 9   SatisfactionScore            1 non-null      int64  
 10  MaritalStatus                1 non-null      object 
 11  NumberOfAddress              1 non-null      int64  
 12  Complain                     1 non-null      int64  
 13  OrderAmountHikeFromLastY

In [6]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer

In [16]:
trf1 = ColumnTransformer([('Categorical_column_OHE', OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'),
                               [1, 4, 5, 8,9])], remainder='passthrough')
trf2 = ColumnTransformer([('scale', StandardScaler(), slice(0, 24))])

In [17]:
input_transformed = trf1.fit_transform(input_df)

In [18]:
input_transformed

array([[12, 1, 2, 2, 3, 'single', 3, 0, 13.0, 10, 20, 160.0]],
      dtype=object)

In [24]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Define the data and columns
data = [12, 'desktop', 1, 2, 'credit card', 'male', 2, 3, 'fashion', 2, 'single', 3, 0, 13.0, 10, 20, 160.0]
columns = ['Tenure', 'PreferredLoginDevice', 'CityTier', 'WarehouseToHome', 'PreferredPaymentMode', 'Gender',
           'HourSpendOnApp', 'NumberOfDeviceRegistered', 'PreferredOrderCat', 'SatisfactionScore',
           'MaritalStatus', 'NumberOfAddress', 'Complain', 'OrderAmountHikeFromLastYear', 'OrderCount',
           'DaySinceLastOrder', 'CashbackAmount']

# Create a DataFrame from the input data
input_df = pd.DataFrame([data], columns=columns)

# Define the categorical columns to encode and their indices
categorical_columns = ['PreferredLoginDevice', 'PreferredPaymentMode', 'Gender', 'PreferredOrderCat', 'MaritalStatus']
categorical_indices = [1, 4, 5, 8, 10]  # Based on the DataFrame

# Build the ColumnTransformer with OneHotEncoder for categorical columns
trf1 = ColumnTransformer([
    ('Categorical_column_OHE', OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'), categorical_indices)
], remainder='passthrough')

# Transform the input data
input_transformed = trf1.fit_transform(input_df)

# Output the transformed data
print(input_transformed)
print(input_transformed.shape)


[[ 12.   1.   2.   2.   3.   2.   3.   0.  13.  10.  20. 160.]]
(1, 12)


In [20]:
# type(input_transformed)

numpy.ndarray

In [21]:
# np.array([[ 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 12.0, 1.0, 2.0, 2.0, 3.0, 0.0, 13.0, 10.0, 20.0, 160.0]])


array([[  1.,   0.,   1.,   0.,   0.,   1.,   0.,  12.,   1.,   2.,   2.,
          3.,   0.,  13.,  10.,  20., 160.]])

In [22]:
input_scaled = trf2.fit_transform(input_transformed)
input_scaled

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Define the data and columns
data = [12, 'desktop', 1, 2, 'credit card', 'male', 2, 3, 'fashion', 2, 'single', 3, 0, 13.0, 10, 20, 160.0]
columns = ['Tenure', 'PreferredLoginDevice', 'CityTier', 'WarehouseToHome', 'PreferredPaymentMode', 'Gender',
           'HourSpendOnApp', 'NumberOfDeviceRegistered', 'PreferredOrderCat', 'SatisfactionScore',
           'MaritalStatus', 'NumberOfAddress', 'Complain', 'OrderAmountHikeFromLastYear', 'OrderCount',
           'DaySinceLastOrder', 'CashbackAmount']

# Create a DataFrame from the input data
input_df = pd.DataFrame([data], columns=columns)

# Define the categorical columns to encode and their indices
categorical_columns = ['PreferredLoginDevice', 'PreferredPaymentMode', 'Gender', 'PreferredOrderCat', 'MaritalStatus']
categorical_indices = [1, 4, 5, 8, 10]  # Based on the DataFrame

# Build the ColumnTransformer with OneHotEncoder for categorical columns
trf1 = ColumnTransformer([
    ('Categorical_column_OHE', OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'), categorical_indices)
], remainder='passthrough')

# Transform the input data
input_transformed = trf1.fit_transform(input_df)

# Output the transformed data and its shape
print("Transformed Data:\n", input_transformed)
print("Transformed Data Shape:", input_transformed.shape)

# Check the categories from OneHotEncoder
encoder = trf1.named_transformers_['Categorical_column_OHE']
print("Categories for OneHotEncoder:", encoder.categories_)
input_scaled = trf2.fit_transform(input_transformed)
print(input_scaled)


Transformed Data:
 [[ 12.   1.   2.   2.   3.   2.   3.   0.  13.  10.  20. 160.]]
Transformed Data Shape: (1, 12)
Categories for OneHotEncoder: [array(['desktop'], dtype=object), array(['credit card'], dtype=object), array(['male'], dtype=object), array(['fashion'], dtype=object), array(['single'], dtype=object)]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
import pickle

In [27]:
import pickle

# Path to the model file
model_path = r'D:\cs_soft_ds_project\churn_model_development\models\model.pkl'

# Load the model using pickle
with open(model_path, 'rb') as file:
    model = pickle.load(file)

print("Model loaded successfully!")

# Example: Make predictions using the model
# Assume you have preprocessed input data `input_data`
# input_data should be in the same format as what the model expects after preprocessing

# input_data = your preprocessed data, for example, from your frontend or another function
# input_array = np.array([input_data])

# Example prediction (replace input_array with your actual input)
# prediction = model.predict(input_array)
# print("Prediction:", prediction)


Model loaded successfully!


In [28]:
model.predict(input_scaled)

ValueError: X has 12 features, but ColumnTransformer is expecting 17 features as input.